### PR TITLE
I am tired of out of memory errors

### PR DESCRIPTION
**Pull request by MRandl**

### CODE REVIEW

**Review by MrZaiko — APPROVED** [review]

**Review by AttiaYoussef — COMMENTED** [review]
Will this help get rid of Out of memories?

**Comment by MRandl** [comment]
> 
> 
> Will this help get rid of Out of memories?

I'm trying to redo every major commit to identify the source of the problem

**Comment by AttiaYoussef** [comment]
> 
> 
> > Will this help get rid of Out of memories?
> 
> I'm trying to redo every major commit to identify the source of the problem

Okay

**Comment by MRandl** [comment]
This passes CI with no problems. I am now sexually aroused.

**Comment by MRandl** [comment]
So what's been causing massive OOMs all along was ... the logout button and 3 lines of xml ? My head hurts

**Comment by MRandl** [comment]
Had to rebase because for some reason cirrus crashes systematically when I add a logout button.

**Review by AttiaYoussef — APPROVED** [review]

**Pull request merged**
