### PR TITLE
Images

### PR DESCRIPTION
**Pull request by MRandl**

### CODE REVIEW

**Review by AttiaYoussef — CHANGES_REQUESTED** [review]
Looks good, but lacks some javadoc.

**Comment by MRandl** [comment]
> Looks good, but lacks some javadoc.

done ;)

**Review by AttiaYoussef — APPROVED** [review]
Looks good enough.

**Review by tombenamato — COMMENTED** [review]
Look good

**Review by Morpheo1 — APPROVED** [review]
Everything looks good and well documented

**Pull request merged**
